/*
 * generated by Xtext
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BeanDslUiModule extends org.xtext.example.ui.AbstractBeanDslUiModule {
	public BeanDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
