/*
 * generated by Xtext
 */
package org.xtext.example;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BeanDslStandaloneSetup extends BeanDslStandaloneSetupGenerated{

	public static void doSetup() {
		new BeanDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

